Repository c137santos/FATEC-API-3-SEMESTRE, pull requests merged in 2024-10, with the labels that each got.

#57 49 adicionar portais de notcias
  backend/src/main/java/com/group/backend/config/WebConfiguration.java
  backend/src/main/java/com/group/backend/controller/ApiController.java
  backend/src/main/java/com/group/backend/controller/PortalController.java
  backend/src/main/java/com/group/backend/controller/TagController.java
  backend/src/main/java/com/group/backend/cron/Cron.java
  backend/src/main/java/com/group/backend/domain/ApiPublicaRepository.java
  backend/src/main/java/com/group/backend/domain/DadosCadastroPortal.java
  backend/src/main/java/com/group/backend/domain/PortalRepository.java
  backend/src/main/java/com/group/backend/domain/ResultApiRepository.java
  backend/src/main/java/com/group/backend/domain/TagPortalRepository.java
  backend/src/main/java/com/group/backend/entity/Portal.java
  backend/src/main/java/com/group/backend/entity/Reporter.java
  backend/src/main/java/com/group/backend/entity/Tag.java
  backend/src/main/java/com/group/backend/entity/TagPortal.java
  backend/src/main/java/com/group/backend/entity/TagPortalId.java
  backend/src/main/java/com/group/backend/service/TagPortalService.java
  backend/src/main/java/com/group/backend/service/TagService.java
  frontend/src/components/AdicionarPortal.vue
  frontend/src/views/PortaisView.vue
Labels: enhancement

#61 :bug: Correcao bugs quando adiciona portais
  backend/src/main/java/com/group/backend/controller/PortalController.java
  backend/src/main/java/com/group/backend/domain/DadosCadastroPortal.java
  backend/src/main/java/com/group/backend/entity/Portal.java
  frontend/src/components/AdicionarPortal.vue
Labels: bug

#64 🐛 Retirando campos não utilizado de edição de tag
  backend/src/main/java/com/group/backend/domain/DadosAtualizarTag.java
  frontend/src/components/ModalEdicaoTag.vue
Labels: bug

#68 66 - 📝produzir um manual de usuario em Markdown (.md)
  README.md
  documentação/Manual_do_usuario.md
  documentação/assets/cadastraApi.jpeg
  documentação/assets/cadastraPortal.jpeg
  documentação/assets/cadastraTag.jpeg
  documentação/assets/consultaNoticia.jpeg
Labels: documentation

#59 ✨Implementa Botão Editar
  backend/src/main/java/com/group/backend/controller/PortalController.java
  backend/src/main/java/com/group/backend/controller/RegionalismoController.java
  backend/src/main/java/com/group/backend/service/TagPortalService.java
  backend/src/main/resources/static/index.html
  frontend/src/components/AdicionarPortal.vue
  frontend/src/components/ModalEdicaoPortal.vue
  frontend/src/components/ModalEdicaoTag.vue
  frontend/src/views/PortaisView.vue
  frontend/src/views/TagView.vue
Labels: enhancement

#79 ✨ 53-US11 Implementação da edição de Api de terceiro
  backend/src/main/java/com/group/backend/controller/ApiController.java
  backend/src/main/java/com/group/backend/domain/DadosEdicaoApiPublica.java
  backend/src/main/java/com/group/backend/entity/ApiPublica.java
  backend/src/main/java/com/group/backend/entity/Reporter.java
  frontend/src/components/AdicionarApi.vue
  frontend/src/components/ModalEdicaoApi.vue
  frontend/src/components/apisListar.vue
  frontend/src/views/ApisView.vue
Labels: enhancement

#81 🚑️ Fix tag display without back-end response
  frontend/src/components/AdicionarTag.vue
Labels: bug
